import scrollSmooth from "./scroll-smooth.js";
import scrollAnimation from "./scroll-animation.js";
import accordion from "./accordion.js";
import tabNav from "./tabnav.js";
import modal from "./modal.js";
import tooltip from "./tooltip.js";
import dropdownMenu from "./dropdown-menu.js";
import outsideClick from "./outsideClick.js";
import menuMobile from "./menu-mobile.js";
import workTime from "./work-time.js";
import fetchAnimals from "./fetch-animals.js";

scrollSmooth();
scrollAnimation();
accordion();
tabNav();
modal();
tooltip();
dropdownMenu();
outsideClick();
menuMobile();
workTime();
fetchAnimals();
