import initScrollSuave from "./scroll-suave.js";
import initAnimacaoScroll from "./scroll-animacao.js";
import initAccordion from "./accordion.js";
import initTabNav from "./tabnav.js";
import initModal from "./modal.js";
import initTooltip from "./tooltip.js";
import initDropdownMenu from "./dropdown-menu.js";
import outsideClick from "./outsideClick.js";
import initMenuMobile from "./menu-mobile.js";
import initAnimaNumbers from "./anima-numbers.js";

initScrollSuave();
initAnimacaoScroll();
initAccordion();
initTabNav();
initModal();
initTooltip();
initDropdownMenu();
outsideClick();
initMenuMobile();
initAnimaNumbers();
